name: dompetku_application
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0
  lucide_icons: ^0.257.0
  pie_chart: ^5.4.0
  flutter_svg: ^2.0.9 # Tambahan untuk mendukung SVG
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/DompetKu.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Folder untuk gambar, termasuk SVG
